### ISSUE TITLE
Summary Filtering

### ISSUE THREAD

**Issue by jobenjada** [formbricks/design#17]
Hey team!

We need comprehensive filtering on the results summary and response page. 

We need filters for:

- Answers to questions
- Time-based
- User Attribute-based
- Tab-based
- Completed or Not

All of these filters have to work together. The filtered data should be possible to pass to the CSV download.

Here is a mockup:
![grafik](https://github.com/formbricks/design/assets/72809645/f0bedafb-b6bd-4c28-be08-92dffb5b2765)

and mobile:
![grafik](https://github.com/formbricks/design/assets/72809645/e9140786-25fe-4533-a3d0-db2e1754e3b7)

And this explains how the fields would work to achieve the expected filter result:
![grafik](https://github.com/formbricks/design/assets/72809645/d5303f0c-6b12-4f74-97dd-3c28e3580a5a)
![grafik](https://github.com/formbricks/design/assets/72809645/c15686f3-1ce1-4e74-8524-5508be78c230)

Open questions:

1. Completed Toggle: Not really consistent, not sure about the position. Could also be a dropdown next to the date range picker to make sure that this setting also influences the data for the CSV download

Super open for Feedback and suggestions 🙏

**Comment by sirkotsky** [comment]
Thanks @jobenjada!

In an attempt to turn it into a community–designed feature and allow others to contribute to it, let's help anyone who'd be willing to pick this up with bringing some structure to it. 

# SOW
> For anyone who is willing to contribute to designing the filtering feature, this should be a good starting point.

## Problem statement
How might we allow Formbricks users to filter responses by various parameters, gather relevant data, and export it to analyse the insights and make informed decisions?

## Filtering parameters
### Filters
#### Global filters
Apply to all results
- Time (questions submitted within a timeframe);
- Completed (filter out completed results only).

#### Filters
User should be able to filter by the following parameters:
- Questions (answers to particular questions)
- User attributes
- Tags

### Types
@jobenjada I might need your help defining the scope here clearly: your wireframes do show that the user should be able to INCLUDE or EXCLUDE particular values, but it might be good to have a product specs in writing for this. 

## How you can help
### **Conduct a market analysis** 
Review our direct and indirect competitors, as well as some other platforms that provide logical and conditional formatting. For instance, Google Docs have the "Data validation" setting that is somewhat similar;

### **Design components** 
We need a very simple set of components helping select and/or toggle values. It might be dropdowns, toggle buttons, or other, better ways of switching between values. 

Then, we need a good view of how filters will look on the page:
- Add a filter;
- Remove a filter;
- Total number of filters.

I highly recommend looking into dashboards, complex tables, and data analytics tools (tableau, powerBI, etc.) that can provide some inspiration. 

### **Wireframes**
End-to-end wireframes: how will filters look and function as part of the holistic experience, how will user export the CVS file, how will the file be named, etc.

Don't forget to think about edge cases (i.e. "nothing found", "file export failed"). 

### Success criteria
We need to provide a smooth and pleasant experience, with low bounce rate and high usage being the core indicators. 

@jobenjada to advise on the business impact.

## What's in it for you
- Get a chance to work with an experienced design (myself), a PM (@jobenjada), and a group of talented and passionate engineers on a real, live product;
- Have a good, unique portfolio piece that will undoubtedly make your design profile stand out;
- Make an impact on many users and be a part of a thriving, growing community; 
- Learn and pick up new skills. 

It's a great opportunity for a junior designer to tackle a complex product and showcase their skills and passion. If you're interested in taking it up, please let us know here or on our [Discord](https://discord.com/invite/3YFcABF2Ts)

**Comment by jobenjada** [comment]
Is in development:

https://github.com/formbricks/formbricks/pull/474
