### ISSUE TITLE
Display Toasts / Notifications in-app

### ISSUE THREAD

**Issue by jobenjada** [formbricks/design#22]
**Problem**
As a user, I want to use Formbricks targeting logic to display a toast (information banner) in-app to specific segments.

**Solution**
Formbricks is well positioned to display toasts as they are pretty much forms without inputs ;) Since teams already have Formbricks included, we should enable them to display a toast as well.

**Tasks**
- Market Research: Research "Toast" experiences other tools offer
- Do 1 user interview with a founder who requested this feature :)
- Create Wireframes, discuss with Kristian and myself
- Scope it & hand over to dev

Thanks a lot! :))

**Comment by Primeedk** [comment]
Hello i would like to take this up

**Comment by jobenjada** [comment]
we put this on hold bc we we'll cover this functionality in the upcoming app store
